version: "3.8"

services:
  web:
    image: prod_${COMPOSE_PROJECT_NAME}_web
    container_name: prod_${COMPOSE_PROJECT_NAME}_web
    build:
      dockerfile: ./docker/prod/web/Dockerfile
      context: .
    volumes:
      - ./db.sqlite3:/code/db.sqlite3
    restart: always
    tty: true
    env_file:
      - .env
      - prod.env
    expose:
      - "8040"

  nginx:
    image: prod_${COMPOSE_PROJECT_NAME}_nginx
    container_name: prod_${COMPOSE_PROJECT_NAME}_nginx
    build:
      dockerfile: ./docker/prod/nginx/Dockerfile
      context: .
    volumes:
      - static_data:/code/staticfiles
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - web

volumes:
  static_data:
