version: "3.8"

services:
  postgres:
    image: dev_${COMPOSE_PROJECT_NAME}_postgres
    container_name: d_${COMPOSE_PROJECT_NAME}_pg
    build:
      context: ./docker/dev/postgres
    restart: always
    env_file:
      - .env
      - dev.env
    volumes:
      - type: volume
        source: pg_data
        target: /var/lib/postgresql/data/
    ports:
      - "5436:5432"
    networks:
      - backend

  web:
    image: dev_${COMPOSE_PROJECT_NAME}_web
    container_name: d_${COMPOSE_PROJECT_NAME}_web
    build:
      dockerfile: ./docker/dev/web/Dockerfile
      context: .
    restart: always
    tty: true
    env_file:
      - .env
      - dev.env
    volumes:
      - .:/code
    ports:
      - "8012:8012"
      - "8898:8898"
    command: >
      sh -c "python manage.py runserver 0.0.0.0:8012"
    networks:
      - backend

networks:
  backend:
    driver: bridge

volumes:
  pg_data:
