version: "3.8"

services:
  postgres:
    image: ${COMPOSE_PROJECT_NAME}_postgres
    container_name: ${COMPOSE_PROJECT_NAME}_postgres
    build:
      context: ./docker/postgres/dev
    restart: always
    env_file:
      - .env
      - dev.env
      - postgres.env
    volumes:
      - type: volume
        source: postgres_volume
        target: /var/lib/postgresql/data/
    ports:
      - "5436:5432"
    networks:
      - backend

  web:
    image: ${COMPOSE_PROJECT_NAME}_web
    container_name: ${COMPOSE_PROJECT_NAME}_web
    build:
      dockerfile: ./docker/dev/web/Dockerfile
      context: .
    restart: always
    tty: true
    env_file:
      - .env
      - dev.env
      - postgres.env
    volumes:
      - .:/code
    ports:
      - "${WEB_PORT}:${WEB_PORT}"
      - "${DEBUG_PORT}:${DEBUG_PORT}"
    command: >
      sh -c "python manage.py runserver 0.0.0.0:${WEB_PORT}"
    networks:
      - backend

networks:
  backend:
    driver: bridge

volumes:
  postgres_volume:
