version: "3.8"

services:
  web:
    image: prod_${COMPOSE_PROJECT_NAME}_web
    container_name: prod_${COMPOSE_PROJECT_NAME}_web
    build:
      dockerfile: ./docker/prod/web/Dockerfile
      context: .
    restart: always
    tty: true
    env_file:
      - .env
      - prod.env
    volumes:
      - .:/code
      - static_data:/code/staticfiles
    ports:
      - "8040:8040"
    command: >
      sh -c "gunicorn --config './docker/prod/web/gunicorn.conf.py'"

  nginx:
    image: prod_${COMPOSE_PROJECT_NAME}_nginx
    container_name: prod_${COMPOSE_PROJECT_NAME}_nginx
    build:
      dockerfile: ./docker/prod/nginx/Dockerfile
      context: .
    volumes:
      - static_data:/code/staticfiles
    env_file:
      - .env
      - prod.env
    ports:
      - "1337:80"
    depends_on:
      - web

volumes:
  pg_data:
  static_data:
