# -- POETRY CONFIG ----------------------------------------------------------------------

[tool.poetry]
name = "chub"
version = "0.1.0"
description = "Chub"
authors = ["Wayne Lambert <wayne.a.lambert@gmail.com>"]

[tool.poetry.dependencies]
python = "==3.9.10"
Django = "4.1.1"
djangorestframework = "3.13.1"
django-crispy-forms = "1.14.0"
django-storages = "1.13.1"
django-recaptcha = "3.0.0"
django-ses = "3.1.2"
django-sequences = "2.7"
django-localflavor = "==3.1"
django-phonenumber-field = "7.0.0"
phonenumbers = "8.12.55"
psycopg2-binary = "2.9.3"
dj-database-url = "1.0.0"
whitenoise = "6.2.0"
celery = "5.2.7"
redis = "4.3.4"
boto3 = "1.24.72"
gunicorn = "==20.1.0"
googlemaps = "4.6.0"
tablib = "3.1.0"
pytz = "2021.3"
django-htmx = "1.12.2"
Pillow = "9.2.0"
crispy-bootstrap5 = "0.6"
rich = "12.5.1"
requests = "2.28.1"
django-ninja = "0.19.1"

[tool.poetry.group.dev.dependencies]
django-debug-toolbar = "3.6.0"
django-extensions = "3.2.1"
ptvsd = "==4.3.2"
pytest = "7.1.3"
pytest-django = "4.5.2"
pytest-cov = "3.0.0"
pytest-factoryboy = "2.5.0"
mixer = "7.2.2"
hypothesis = "6.54.5"
coverage = "6.4.4"
pycodestyle = "2.9.1"
pylint-django = "2.5.3"
ipdb = "==0.13.9"
bandit = "1.7.4"
interrogate = "1.5.0"
pywatchman = "==1.4.1"
django-browser-reload = "1.6.0"
ipython = "8.5.0"
black = "22.8.0"
pylint = "2.15.0"
bpython = "0.23"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
