# Generated by Django 4.1.2 on 2022-10-13 17:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import pathlib


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name='ID'
                    ),
                ),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=255)),
                ('desc', models.TextField()),
                ('is_priority', models.BooleanField(default=False)),
                (
                    'image',
                    models.ImageField(
                        default=pathlib.PurePosixPath(
                            '/Users/wayne-lambert/dev/django-webpack/src/media/aa_project/static/default_images'
                        ),
                        max_length=200,
                        upload_to='',
                    ),
                ),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                (
                    'created_by',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='tasks',
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                'ordering': ('created_date',),
            },
        ),
    ]
