# Generated by Django 4.1.2 on 2022-10-13 17:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_task_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='image',
        ),
    ]
